# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nba_mcp_fastapi"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: "/metrics"
    scheme: "http"
